name: Deploy S.O.P.R.O (Docker)

on:
  push:
    branches:
      - main
env:
    TAG: 1.0.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/sopro:${{ env.TAG }} .

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/sopro:${{ env.TAG }}

      - name: Deploy no servidor via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USER }}/sopro:${{ env.TAG }}
            docker stop sopro || true
            docker rm sopro || true
            docker run -d --name sopro -p 8080:80 \
              -v /var/www/html/sopro/uploads:/var/www/html/uploads \
              --env DB_HOST=${{ secrets.DB_HOST }} \
              --env DB_USER=${{ secrets.DB_USER }} \
              --env DB_PASS=${{ secrets.DB_PASS }} \
              --env DB_NAME=${{ secrets.DB_NAME }} \
              ${{ secrets.DOCKER_USER }}/sopro:${{ env.TAG }}
            docker exec sopro chown -R www-data:www-data /var/www/html/uploads
            docker exec sopro chmod -R 775 /var/www/html/uploads

      - name: Enviar uploads para o servidor
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "uploads/*"
          target: "/var/www/html/sopro/uploads/"